"""
PayFlow — Regulatory Report PDF Generator
============================================
Generates STR (Suspicious Transaction Report), FMR (Fraud Monitoring Return),
and CTR (Cash Transaction Report) PDFs for RBI / FIU-IND submissions.

Uses fpdf2 for zero-dependency PDF generation with Union Bank of India
header formatting.
"""

from __future__ import annotations

import io
import time
from datetime import datetime


def _ensure_fpdf():
    """Lazy import fpdf2, return the FPDF class."""
    try:
        from fpdf import FPDF
        return FPDF
    except ImportError:
        # Minimal fallback: plain text PDF via raw bytes
        return None


def _header(pdf, title: str) -> None:
    """Standard Union Bank of India report header."""
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Union Bank of India", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "PayFlow Intelligence Center", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, title, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.cell(
        0, 6,
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')}",
        new_x="LMARGIN", new_y="NEXT", align="C",
    )
    pdf.ln(4)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)


def _add_kv(pdf, key: str, value: str) -> None:
    """Add a key-value row."""
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(60, 7, key, border=0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT", border=0)


def _section(pdf, title: str) -> None:
    """Add a section heading."""
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)


def generate_str_pdf(data: dict) -> bytes:
    """
    Generate a Suspicious Transaction Report (STR) PDF.

    Parameters:
        data: dict with keys like account_id, report_id, suspicion_category, etc.

    Returns:
        PDF file content as bytes.
    """
    FPDF = _ensure_fpdf()
    if FPDF is None:
        return _plaintext_pdf("STR Report", data)

    pdf = FPDF()
    pdf.add_page()
    _header(pdf, "Suspicious Transaction Report (STR)")

    _section(pdf, "1. Report Details")
    _add_kv(pdf, "Report ID:", data.get("report_id", "N/A"))
    _add_kv(pdf, "Date Filed:", datetime.now().strftime("%Y-%m-%d"))
    _add_kv(pdf, "Filing Entity:", "Union Bank of India (UBIN)")
    _add_kv(pdf, "Report Type:", "STR - Suspicious Transaction Report")

    _section(pdf, "2. Subject Information")
    _add_kv(pdf, "Account ID:", data.get("account_id", "N/A"))
    _add_kv(pdf, "Account Name:", data.get("account_name", "N/A"))
    _add_kv(pdf, "Category:", data.get("suspicion_category", "ML_FLAGGED"))

    _section(pdf, "3. Suspicious Activity Details")
    _add_kv(pdf, "Total Amount:", f"INR {data.get('total_amount_paisa', 0) / 100:,.2f}")
    _add_kv(pdf, "Transaction Count:", str(len(data.get("txn_ids", []))))
    _add_kv(pdf, "ML Confidence:", f"{data.get('ml_confidence', 0.0):.4f}")

    desc = data.get("suspicion_description", data.get("description", "Flagged by ML pipeline"))
    pdf.set_font("Helvetica", "", 10)
    pdf.ln(2)
    pdf.multi_cell(0, 6, f"Description: {desc}")

    _section(pdf, "4. Transaction IDs")
    txn_ids = data.get("txn_ids", [])
    if txn_ids:
        for tid in txn_ids[:20]:
            pdf.set_font("Courier", "", 9)
            pdf.cell(0, 5, f"  {tid}", new_x="LMARGIN", new_y="NEXT")
        if len(txn_ids) > 20:
            pdf.set_font("Helvetica", "I", 9)
            pdf.cell(0, 5, f"  ... and {len(txn_ids) - 20} more", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 5, "  No specific transactions listed", new_x="LMARGIN", new_y="NEXT")

    _section(pdf, "5. Regulatory Compliance")
    _add_kv(pdf, "Filed Under:", "PMLA Section 12(1)")
    _add_kv(pdf, "Reporting to:", "FIU-IND (Financial Intelligence Unit - India)")
    _add_kv(pdf, "Compliance Officer:", "MLRO, Union Bank of India")

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5,
        "This report was auto-generated by PayFlow Intelligence Center. "
        "Confidential — for regulatory use only.",
        new_x="LMARGIN", new_y="NEXT", align="C",
    )

    return pdf.output()


def generate_fmr_pdf(data: dict) -> bytes:
    """
    Generate a Fraud Monitoring Return (FMR) PDF for RBI submission.

    Parameters:
        data: dict with case_id, fraud_type, amount, etc.

    Returns:
        PDF file content as bytes.
    """
    FPDF = _ensure_fpdf()
    if FPDF is None:
        return _plaintext_pdf("FMR Report", data)

    pdf = FPDF()
    pdf.add_page()
    _header(pdf, "Fraud Monitoring Return (FMR) - RBI")

    _section(pdf, "1. Report Identification")
    _add_kv(pdf, "Case ID:", data.get("case_id", "N/A"))
    _add_kv(pdf, "Reporting Quarter:", datetime.now().strftime("%Y-Q%q").replace(
        "%q", str((datetime.now().month - 1) // 3 + 1),
    ))
    _add_kv(pdf, "Bank Name:", "Union Bank of India")
    _add_kv(pdf, "Bank Code:", "UBIN")

    _section(pdf, "2. Fraud Details")
    _add_kv(pdf, "Fraud Type:", data.get("fraud_type", "Cyber Fraud"))
    _add_kv(pdf, "Channel:", data.get("channel", "Digital Banking"))
    _add_kv(pdf, "Amount Involved:", f"INR {data.get('amount_paisa', 0) / 100:,.2f}")
    _add_kv(pdf, "Amount Recovered:", f"INR {data.get('recovered_paisa', 0) / 100:,.2f}")

    _section(pdf, "3. Detection Details")
    _add_kv(pdf, "Detection Method:", "PayFlow ML + Graph Intelligence")
    _add_kv(pdf, "Detection Date:", data.get("detection_date", datetime.now().strftime("%Y-%m-%d")))
    _add_kv(pdf, "ML Risk Score:", str(data.get("risk_score", "N/A")))
    _add_kv(pdf, "Graph Evidence:", data.get("graph_evidence", "N/A"))

    _section(pdf, "4. Action Taken")
    _add_kv(pdf, "Account Frozen:", data.get("account_frozen", "Yes"))
    _add_kv(pdf, "STR Filed:", data.get("str_filed", "Yes"))
    _add_kv(pdf, "Law Enforcement:", data.get("law_enforcement_notified", "Pending"))

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5,
        "Filed as per RBI Master Direction on Fraud Reporting (DoS.CO.FrMC/2/33.01.001/2023-24). "
        "Confidential.",
        new_x="LMARGIN", new_y="NEXT", align="C",
    )

    return pdf.output()


def generate_ctr_pdf(data: dict) -> bytes:
    """
    Generate a Cash Transaction Report (CTR) PDF.

    Parameters:
        data: dict with account_id, amount, txn_id, etc.

    Returns:
        PDF file content as bytes.
    """
    FPDF = _ensure_fpdf()
    if FPDF is None:
        return _plaintext_pdf("CTR Report", data)

    pdf = FPDF()
    pdf.add_page()
    _header(pdf, "Cash Transaction Report (CTR)")

    _section(pdf, "1. Transaction Details")
    _add_kv(pdf, "Transaction ID:", data.get("txn_id", "N/A"))
    _add_kv(pdf, "Account ID:", data.get("account_id", "N/A"))
    _add_kv(pdf, "Account Name:", data.get("account_name", "N/A"))
    _add_kv(pdf, "Amount:", f"INR {data.get('amount_paisa', 0) / 100:,.2f}")

    _section(pdf, "2. Reporting Threshold")
    _add_kv(pdf, "Threshold:", "INR 10,00,000 (Cash) / INR 50,00,000 (Wire)")
    _add_kv(pdf, "Report Filed:", datetime.now().strftime("%Y-%m-%d %H:%M IST"))
    _add_kv(pdf, "Reporting Entity:", "Union Bank of India (UBIN)")

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5,
        "Filed under PMLA Rule 3 — CTR for transactions above threshold. Confidential.",
        new_x="LMARGIN", new_y="NEXT", align="C",
    )

    return pdf.output()


def _plaintext_pdf(title: str, data: dict) -> bytes:
    """Fallback: generate a minimal PDF without fpdf2."""
    lines = [f"=== {title} ===", ""]
    for k, v in data.items():
        lines.append(f"{k}: {v}")
    lines.append("")
    lines.append(f"Generated: {datetime.now().isoformat()}")
    content = "\n".join(lines)

    # Minimal PDF 1.4 structure
    body = content.encode("latin-1", errors="replace")
    pdf_parts = []
    pdf_parts.append(b"%PDF-1.4\n")
    # Catalog
    pdf_parts.append(b"1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n")
    # Pages
    pdf_parts.append(b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n")
    # Page
    pdf_parts.append(
        b"3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]"
        b"/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj\n"
    )
    # Stream
    stream = b"BT /F1 10 Tf 50 740 Td 12 TL\n"
    for line in content.split("\n"):
        safe = line.encode("latin-1", errors="replace")
        stream += b"(" + safe.replace(b"(", b"\\(").replace(b")", b"\\)") + b") '\n"
    stream += b"ET\n"
    pdf_parts.append(
        f"4 0 obj<</Length {len(stream)}>>stream\n".encode()
        + stream + b"endstream endobj\n"
    )
    # Font
    pdf_parts.append(
        b"5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Courier>>endobj\n"
    )
    # Xref + trailer (simplified)
    full = b"".join(pdf_parts)
    xref_pos = len(full)
    full += f"xref\n0 6\n0000000000 65535 f \n".encode()
    full += b"trailer<</Size 6/Root 1 0 R>>\n"
    full += f"startxref\n{xref_pos}\n%%EOF\n".encode()
    return full
